### PR TITLE
Ability to switch angular waiting on and off

### PR DESCRIPTION
**Pull request by nicsnoek**
I have been using this for some time now and find it very useful.

### CODE REVIEW

**Comment by nicsnoek** [comment]
Oh, I just noticed there already is a pull request for similar functionality. Perhaps this is a bit more intuitive to use, but requires more code.

**Comment by vvo** [comment]
Yes and you should be able to do it like this: https://github.com/webdriverio/webdriverjs-angular/pull/3#issuecomment-93751521

**Comment by nicsnoek** [comment]
So how would that for eg. a setValue, now that internally it uses elements that have been decorated to wait for angular?

**Comment by vvo** [comment]
True! Now I get it, and that's a nice API you are introducing. Do you think we could write tests for it?

**Comment by nicsnoek** [comment]
Yes, tests seem very reasonable :-) stay tuned...

**Comment by nicsnoek** [comment]
Very interesting. You are right, only the url is required. The wait returns immediately even if left in as either angular is not defined in the case where angular is not loaded, or angular.element(el).injector() returns null in the case where there is no angular app. It all comes out in the wash. The wait script returns an error, but no one cares :-). To neaten it up, I have defined the following, works like a charm:

```javascript
client.addCommand('nonAngularUrl', function(value, cb) {
    var WebdriverIO = require('webdriverio/lib/webdriverio');
    WebdriverIO.prototype.url.call(this, value, cb);
});
```

**Comment by christian-bromann** [comment]
Awesome, thanks for sharing @nicsnoek

**Pull request closed without merging**
